---
sidebar: sidebar 
permalink: faq-cloud-tiering.html 
keywords: faq, questions, requirements, service connector, object store, object storage, aws, azure, bucket, cluster, aggregate, s3, storage class, standard, inactive data reporting, auto, volume tiering policy, policy, tiering policy, snapshot, cold, inactive, infrequent 
summary: 如果您只是想要快速回答問題、這個常見問題集就能幫上忙。 
---
= 雲端分層技術常見問題集
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
如果您只是想要快速回答問題、這個常見問題集就能幫上忙。



== ONTAP

下列問題 ONTAP 與不相關。



=== 我的整個叢集有哪些需求 ONTAP ？

這取決於您分層 Cold 資料的位置。請參閱下列內容：

* link:task-tiering-onprem-aws.html#preparing-your-ontap-clusters["將內部部署 ONTAP 的資料叢集分層至 Amazon S3"]
* link:task-tiering-onprem-azure.html#preparing-your-ontap-clusters["將內部部署 ONTAP 的資料叢集分層至 Azure Blob 儲存設備"]
* link:task-tiering-onprem-gcp.html#preparing-your-ontap-clusters["將內部部署 ONTAP 的資料叢集分層至 Google Cloud Storage"]
* link:task-tiering-onprem-storagegrid.html#preparing-your-ontap-clusters["將內部部署 ONTAP 的資料叢集分層至 StorageGRID 不再需要"]
* link:task-tiering-onprem-s3-compat.html#preparing-your-ontap-clusters["將內部部署ONTAP 的資料叢集分層、以儲存S3物件"]




=== 支援哪些類型的不完整系統？ONTAP

單節點和高可用度AFF 的堆疊支援雲端分層功能、包括：FAS ONTAP Select也支援使用「鏡射鏡射」組態的叢集FabricPool 、但組態必須使用System Manager或ONTAP CLI來完成。



=== 雲端分層是否能啟用非作用中的資料報告？

是的、雲端分層可在每個 Aggregate 上啟用非作用中資料報告。此設定可讓我們識別可分層至低成本物件儲存的非使用中資料量。


NOTE: 如果叢集執行 ONTAP 的是 32 或更新版本、雲端分層可在 HDD 集合體上啟用非作用中資料報告功能。



=== 我可以從 NAS 磁碟區和 SAN 磁碟區來分層資料嗎？

您可以將資料從NAS磁碟區分層到公有雲或私有雲、例如StorageGRID ：在分層SAN傳輸協定存取的資料時、NetApp建議使用私有雲端、因為連線考量。



=== 關於此功能呢 Cloud Volumes ONTAP ？

如果您使用 Cloud Volumes ONTAP 的是 NetApp 系統、您可以在叢集儀表板中找到這些系統、以便在混合雲基礎架構中完整檢視資料分層。

從叢集儀表板、您可以檢視與內部 ONTAP 叢集類似的分層資訊：作業健全狀況、目前的節約效益、節約機會、磁碟區與集合體的詳細資料等。

從 Cloud Tiering 讀取系統。 Cloud Volumes ONTAP您無法從 Cloud Volumes ONTAP Cloud Tiering 設定資料分層功能。 https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-tiering.html["您可以在 Cloud Volumes ONTAP Cloud Manager 中設定針對運作環境的效能提升"^]。



== 物件儲存

下列問題與物件儲存有關。



=== 支援哪些物件儲存供應商？

雲端分層支援下列物件儲存供應商：

* Amazon S3
* Microsoft Azure Blob
* Google Cloud Storage
* NetApp StorageGRID
* S3相容的物件儲存設備
* IBM Cloud物件儲存設備（FabricPool 但必須使用System Manager或ONTAP CLI完成此功能的不實組態設定）




=== 我可以使用自己的桶 / 容器嗎？

是的、您可以。當您設定資料分層時、可以選擇新增庫位 / 容器、或是選取現有的庫位 / 容器。



=== 支援哪些地區？

* link:reference-aws-support.html["支援的 AWS 區域"]
* link:reference-azure-support.html["支援的 Azure 地區"]
* link:reference-google-support.html["支援的 Google Cloud 地區"]




=== 支援哪些 S3 儲存類別？

雲端分層可支援資料分層至_Standard_、_Standard-in頻繁 存取_、_one Zone非常用存取_、_Intelligent Tiering _和_Glacier即時擷取_儲存類別。請參閱 link:reference-aws-support.html["支援的 S3 儲存類別"] 以取得更多詳細資料。



=== 支援哪些 Azure Blob 存取層？

雲端分層可將資料分層至_hot_或_cool _存取層、以供非使用中資料使用。請參閱 link:reference-azure-support.html["支援的 Azure Blob 存取層"] 以取得更多詳細資料。



=== Google Cloud Storage 支援哪些儲存類別？

雲端分層支援資料分層至_Standard_、_Nearlin__、_Coldlin__和_Archive_儲存類別。請參閱 link:reference-google-support.html["支援的Google Cloud儲存類別"] 以取得更多詳細資料。



=== 雲端分層會將一個物件存放區用於整個叢集、還是每個 Aggregate 使用一個物件存放區？

一個物件存放區用於整個叢集。



=== 我可以將原則套用到物件存放區、以便在分層不受限制的情況下移動資料嗎？

是的。您可以啟用生命週期管理、以便在特定天數後、將資料從預設儲存類別/存取層移轉至更具成本效益的層級。

生命週期規則會套用至Amazon S3和Google Cloud儲存設備所選儲存區中的所有物件、以及Azure Blob所選儲存帳戶中的所有容器。



== 連接器

下列問題與連接器有關。



=== 連接器需要安裝在何處？

* 將資料分層至S3時、連接器可位於AWS VPC或內部部署環境中。
* 將資料分層至Blob儲存設備時、Connector可位於Azure vnet或內部部署環境中。
* 將資料分層至Google Cloud Storage時、Connector必須位於Google Cloud Platform VPC中。
* 將資料分層至StorageGRID 不支援功能或其他S3的儲存供應商時、連接器必須位於內部部署環境中。




== 網路

下列問題與網路有關。



=== 網路需求為何？

* 此支援叢集可透過連接埠 443 、啟動 HTTPS 連線至您的物件儲存設備供應商。 ONTAP
+
可在物件儲存設備中讀取及寫入資料。 ONTAP物件儲存設備從未啟動、只是回應而已。

* 對於 StorageGRID 僅供使用的物件、 ONTAP 支援使用者指定的連接埠來啟動 HTTPS 連線 StorageGRID 至物件（連接埠可在分層設定期間設定）。
* 連接器需要透過連接埠 443 連至 ONTAP 您的叢集、物件存放區和雲端分層服務的輸出 HTTPS 連線。


如需詳細資料、請參閱：

* link:task-tiering-onprem-aws.html["將內部部署 ONTAP 的資料叢集分層至 Amazon S3"]
* link:task-tiering-onprem-azure.html["將內部部署 ONTAP 的資料叢集分層至 Azure Blob 儲存設備"]
* link:task-tiering-onprem-gcp.html["將內部部署 ONTAP 的資料叢集分層至 Google Cloud Storage"]
* link:task-tiering-onprem-storagegrid.html["將內部部署 ONTAP 的資料叢集分層至 StorageGRID 不再需要"]
* link:task-tiering-onprem-s3-compat.html["將內部部署ONTAP 的資料叢集分層、以儲存S3物件"]




== 權限

下列問題與權限有關。



=== AWS 需要哪些權限？

需要權限 link:task-tiering-onprem-aws.html#preparing-amazon-s3["管理 S3 儲存區"]。



=== Azure 需要哪些權限？

您不需要在 Cloud Manager 所需的權限範圍之外、額外權限。



=== Google Cloud Platform 需要哪些權限？

需要儲存管理員權限才能執行 link:task-tiering-onprem-gcp.html#preparing-google-cloud-storage["具有儲存存取金鑰的服務帳戶"]。



=== 需要哪些權限 StorageGRID 才能執行此功能？

link:task-tiering-onprem-storagegrid.html#preparing-storagegrid["需要 S3 權限"]。



=== S3相容物件儲存需要哪些權限？

link:task-tiering-onprem-s3-compat.html#preparing-s3-compatible-object-storage["需要 S3 權限"]。
